version: '3'
services:
  # Node
  node:
    image: node:14-alpine
    volumes:
      - ./:/var/www
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    working_dir: /var/www
    tty: true

  # Mailer
  mailer:
    image: mailhog/mailhog
    ports:
      - "8082:8025"
      - "1025:1025"
